### ISSUE TITLE
Add sonarr, prowlarr, and radarr to Gentoo

### ISSUE THREAD

**Issue by candrews** [xartin/gentoo-overlay#11]
I'm a developer with Gentoo. I'd like to add sonarr, prowlarr, and radarr to official Gentoo.

Would you like to submit a MR to https://github.com/gentoo/gentoo/ adding these packages? If so, please do so and in `metadata.xml` mark me as `maintainer` and yourself as proxy maintainer, like this:
```xml
<maintainer type="person" proxied="yes">
	<email>mcrawford@eliteitminds.com</email>
	<name>Mike Crawford</name>
	<description>Primary maintainer</description>
</maintainer>
<maintainer type="project" proxied="proxy">
	<email>proxy-maint@gentoo.org</email>
	<name>Proxy Maintainers</name>
</maintainer>
<maintainer type="person">
	<email>candrews@gentoo.org</email>
	<name>Craig Andrews</name>
</maintainer>
```

These packages look quite well done so I don't think there will be much effort to get them included.

Thank you so much for this effort and I look forward to working with you going forward!

**Comment by candrews** [comment]
I've made an MR: https://github.com/gentoo/gentoo/pull/26247

I'm eager to receive your feedback

**Comment by xartin** [comment]
There's one dependency problem with arm64 that needs to be resolved. mediainfo and libmediainfo need to be ~arch keyworded

Neddy had a PR waiting for that last i looked that had not yet been completed or reviewed.

https://github.com/gentoo/gentoo/pull/25774

This is needed for sonarr or radarr to function iirc.

I was waiting for that PR to process then I was going to complete the dependency or repoman QA checks in my own repo where that shouldn't have affected many people since arm64 was all new ebuild code recently but this MR has made the desirability of that QA more important.

If you can investigate the mediainfo PR that could be beneficial to merging these packages.

**Comment by xartin** [comment]
@candrews i just noticed i was email spammed earlier today with 13 bugzilla emails about unresolved soname dependencies ldflags and cflags for all of these packages that were merged. I suspect these aren't a concern since all of the arr's packages are precompiled binaries?

![untitled](https://user-images.githubusercontent.com/20513061/178179007-2bd9136a-65cf-46ca-8461-735eaec203ff.png)

**Comment by candrews** [comment]
Yeah... That was a lot of email!

As you said, because these are bikary packages, the ldflags and cflags qa issues aren't a concern. I'll suppress those in the ebuilds and close those issues tomorrow.

The unresolved sonames ones warrant further investigation. The packages seem to work fine, so these don't appear to be significant problems, but I'd still like to address them if possible.

**Comment by candrews** [comment]
These packages are now in Gentoo: https://github.com/gentoo/gentoo/pull/26247
